import { PortfolioData } from "@/types/portfolio";

export const fallbackPortfolioData: PortfolioData = {
  profile: {
    id: 1,
    full_name: "Tharun Vaibhav S S",
    primary_title: "Software Engineer | AI, Data & IoT",
    brand_slogan: "Wild Idea. Wealthy Innovation.",
    email: "tharunvaibhavsaminathan@gmail.com",
    phone: "+91 87600 85142",
    location: "Erode, Tamil Nadu",
    short_bio:
      "Software engineer specializing in AI, Data & Analytics, IoT systems, and full-stack software development. Passionate about turning wild ideas into wealthy, scalable engineering innovations.",
    full_about:
      "I am an MCA scholar and software engineer with a distinct focus on building practical physical-digital systems. My engineering philosophy—'Wild Idea. Wealthy Innovation.'—bridges fearless curiosity, hands-on experimentation, and rigorous software craftsmanship. Whether architecting AI-assisted industrial machine diagnostics with FastAPI and Next.js, capturing multi-sensor IoT telemetry for real-time anomaly detection, or optimizing enterprise ERP data pipelines with SQL, I design systems that solve tangible problems and deliver measurable results.",
    portrait_url: "/photos/tharun_vaibhav_portrait.jpg",
    is_active: true,
  },
  social_links: [
    {
      id: 1,
      platform: "GitHub",
      url: "https://github.com/tharunvaibhavss",
      display_label: "github.com/tharunvaibhavss",
      icon_name: "github",
      display_order: 1,
    },
    {
      id: 2,
      platform: "LinkedIn",
      url: "https://www.linkedin.com/in/tharun-vaibhav-s-s",
      display_label: "linkedin.com/in/tharun-vaibhav-s-s",
      icon_name: "linkedin",
      display_order: 2,
    },
    {
      id: 3,
      platform: "Email",
      url: "mailto:tharunvaibhavsaminathan@gmail.com",
      display_label: "tharunvaibhavsaminathan@gmail.com",
      icon_name: "mail",
      display_order: 3,
    },
    {
      id: 4,
      platform: "Phone",
      url: "tel:+918760085142",
      display_label: "+91 87600 85142",
      icon_name: "phone",
      display_order: 4,
    },
  ],
  education: [
    {
      id: 1,
      degree: "Master of Computer Application (MCA)",
      institution: "PSG College of Arts & Science",
      score: "78%*",
      completion_date: "May 2027",
      start_date: "2025",
      description:
        "Specializing in Artificial Intelligence, Generative AI, LLM-powered applications, Python, Data & Analytics, and IoT system architecture.",
      display_order: 1,
    },
    {
      id: 2,
      degree: "B.Sc Information Technology",
      institution: "PSG College of Arts & Science",
      score: "75.9%",
      completion_date: "May 2025",
      start_date: "2022",
      description:
        "Focused on Computer Science fundamentals, Software Engineering, Database Systems, Web Technologies, and IoT.",
      display_order: 2,
    },
    {
      id: 3,
      degree: "Higher Secondary (12th Grade)",
      institution: "Velalar Vidyalayaa Senior Secondary School",
      score: "78.6%",
      completion_date: "May 2022",
      start_date: "2020",
      description: "Higher Secondary Education with focus on Science and Mathematics.",
      display_order: 3,
    },
    {
      id: 4,
      degree: "Secondary School Examination (10th Grade)",
      institution: "Velalar Vidyalayaa Senior Secondary School",
      score: "78.8%",
      completion_date: "March 2020",
      start_date: "2018",
      description: "Secondary School Curriculum covering Core Science, Mathematics, and Computer Applications.",
      display_order: 4,
    },
  ],
  experience: [
    {
      id: 1,
      company: "Dyzen Consultants",
      role: "Software Development Intern",
      duration: "10 Months",
      year: "2026",
      location: "Remote / Hybrid",
      bullet_points: [
        "Developed and deployed 4+ web applications and responsive client platforms, contributing to full lifecycle development, testing, maintenance, and reliable software delivery.",
        "Performed comprehensive debugging, issue tracking, and performance optimization to ensure high uptime and responsive interaction across viewports.",
        "Collaborated with cross-functional teams to understand client specifications, investigate technical bottlenecks, and implement practical solutions.",
        "Applied user behavior analytics and targeted UI/UX refinements, achieving a 25–30% reduction in website bounce rates.",
        "Engineered digital solutions using WordPress, Figma, CSS architectures, and modern web best practices.",
      ],
      tech_tags: ["Next.js", "WordPress", "Figma", "UI/UX", "SEO", "Web Analytics"],
      display_order: 1,
    },
    {
      id: 2,
      company: "Thiruvusoft",
      role: "ERP Software Development Intern",
      duration: "2 Weeks",
      year: "2025",
      location: "Coimbatore, India",
      bullet_points: [
        "Streamlined core ERP workflows using custom SQL queries and data transformation techniques across Finance, Inventory, and HR modules.",
        "Reduced manual processing overhead by 15–20% through structured, automated SQL-based data handling routines.",
        "Assisted in improving data pipeline efficiency and transactional data integrity across enterprise modules by 30%, enhancing reporting reliability.",
      ],
      tech_tags: ["SQL", "ERP Workflows", "Data Pipelines", "Database Optimization"],
      display_order: 2,
    },
    {
      id: 3,
      company: "Akkroni Craft",
      role: "Software Developer Intern",
      duration: "20 Days",
      year: "2025",
      location: "India",
      bullet_points: [
        "Strengthened digital presence by optimizing website information architecture through SEO best practices and traffic analytics.",
        "Enhanced brand communication workflows by engineering responsive email templates and corporate collateral using structured content strategies.",
      ],
      tech_tags: ["Web Optimization", "SEO", "Email Templates", "Content Strategy"],
      display_order: 3,
    },
  ],
  projects: [
    {
      id: 1,
      slug: "cat-industrial-diagnostic-system",
      title: "AI-Powered Industrial Machine Diagnostic System",
      tagline: "End-to-End Predictive Maintenance & Telemetry Intelligence Platform",
      year: "2026",
      organization: "PSGCAS",
      description:
        "A comprehensive full-stack industrial diagnostic system engineered for real-time equipment telemetry monitoring, predictive fault analysis, work order dispatch, and automated maintenance reporting.",
      problem:
        "Industrial factories suffer catastrophic downtime when heavy machinery components fail without warning. Fragmented maintenance logs and manual triage slow technician response times.",
      solution:
        "Constructed a unified telemetry processing platform that ingests machine sensor metrics, runs vision and manual inspection routines, and leverages OpenAI GPT-5.5 API to provide instant diagnosis and actionable repair playbooks.",
      contribution:
        "Architected backend REST microservices with FastAPI and PostgreSQL/SQLAlchemy, implemented JWT role-based access control, integrated OpenAI LLM reasoning pipelines, and created automated PDF incident reports.",
      measurable_results:
        "Structured diagnostic triage workflows into automated protocols with instant AI recommendations.",
      github_url: "https://github.com/tharunvaibhavss/cat",
      live_url: undefined,
      featured: true,
      display_order: 1,
      primary_category: "AI",
      technologies: [
        { id: 1, name: "Next.js", category: "Frontend" },
        { id: 2, name: "FastAPI", category: "Backend" },
        { id: 3, name: "Python", category: "Language" },
        { id: 4, name: "PostgreSQL", category: "Database" },
        { id: 5, name: "SQLAlchemy", category: "ORM" },
        { id: 6, name: "OpenAI API (GPT-5.5)", category: "AI/ML" },
        { id: 7, name: "JWT Auth", category: "Security" },
        { id: 8, name: "Automated PDF Engine", category: "Reporting" },
      ],
    },
    {
      id: 2,
      slug: "enervision-ai-energy-audit",
      title: "Enervision – AI Energy Audit System",
      tagline: "IoT Telemetry & Predictive Anomaly Detection for Industrial Power Grids",
      year: "2026",
      organization: "PSGCAS",
      description:
        "An AI and IoT-driven energy audit platform engineered for live industrial power consumption tracking, anomaly detection, predictive load forecasting, and sustainability audits.",
      problem:
        "Commercial and factory facilities leak electricity through phantom loads, unbalanced phases, and aging machinery, resulting in uncontrolled operational costs and carbon waste.",
      solution:
        "Built a dual-tier architecture pairing IoT hardware sensor nodes with a Python predictive analytics engine to monitor live energy flow, detect anomalous spikes, and forecast consumption cycles.",
      contribution:
        "Developed real-time sensor ingestion scripts in Python, trained predictive time-series models for energy forecasting, and built interactive dashboards for facility managers.",
      measurable_results:
        "Demonstrated 20–25% potential energy savings through automated anomaly alerts and usage optimization.",
      github_url: "https://github.com/tharunvaibhavss/enervision",
      live_url: undefined,
      featured: true,
      display_order: 2,
      primary_category: "DATA",
      technologies: [
        { id: 9, name: "Python", category: "Language" },
        { id: 10, name: "IoT Sensors", category: "Hardware" },
        { id: 11, name: "Predictive Modeling", category: "AI/ML" },
        { id: 12, name: "Anomaly Detection", category: "Algorithms" },
        { id: 13, name: "Power BI / Dashboards", category: "Analytics" },
        { id: 14, name: "Sustainability Auditing", category: "Domain" },
      ],
    },
    {
      id: 3,
      slug: "client-website-projects",
      title: "Client Website Projects Portfolio",
      tagline: "Suite of High-Performance Business Platforms & Client Solutions",
      year: "2026",
      organization: "Dyzen Consultants",
      description:
        "A curated collection of 4+ production client websites and business web applications developed to enhance digital presence, conversion funnels, and organic search ranking.",
      problem:
        "Small and medium enterprises required modern, mobile-first web platforms with high speed, structured SEO schema, and intuitive user experiences to reduce high bounce rates.",
      solution:
        "Engineered custom responsive interfaces utilizing modern CSS architectures, WordPress customizations, Figma design specifications, and performance optimization pipelines.",
      contribution:
        "Handled full-cycle design-to-deployment, implementing accessibility audits, structured schema markup, and cross-browser testing.",
      measurable_results:
        "Directly contributed to a 25–30% reduction in user bounce rates across delivered client sites.",
      github_url: "https://github.com/tharunvaibhavss/websites",
      live_url: undefined,
      featured: true,
      display_order: 3,
      primary_category: "SOFTWARE",
      technologies: [
        { id: 15, name: "HTML5 & CSS3", category: "Frontend" },
        { id: 16, name: "JavaScript", category: "Language" },
        { id: 17, name: "WordPress", category: "CMS" },
        { id: 18, name: "Figma", category: "Design" },
        { id: 19, name: "SEO Optimization", category: "Analytics" },
        { id: 20, name: "Hostinger / Vercel", category: "Deployment" },
      ],
    },
    {
      id: 4,
      slug: "water-quality-monitoring-system",
      title: "Water Quality Monitoring System (WQT)",
      tagline: "Multi-Parameter IoT Environmental Sensing Rig",
      year: "2025",
      organization: "PSGCAS",
      description:
        "An IoT environmental sensing system built to capture, analyze, and stream live water quality parameters including pH, total dissolved solids (TDS), turbidity, and temperature.",
      problem:
        "Manual chemical testing of water reservoirs is intermittent and incapable of instantly warning communities or plants about sudden toxic discharges or contamination.",
      solution:
        "Designed an automated hardware sensing rig that submerges multi-parameter sensors and transmits calibrated telemetry to a Python data-logging and visualization interface.",
      contribution:
        "Configured microcontrollers and analog sensor inputs, wrote calibration routines for pH and TDS probes, and built automated Python analytics scripts.",
      measurable_results:
        "Enabled continuous 24/7 environmental telemetry logging with real-time threshold alert triggers.",
      github_url: "https://github.com/tharunvaibhavss/wqt",
      live_url: undefined,
      featured: false,
      display_order: 4,
      primary_category: "IoT",
      technologies: [
        { id: 21, name: "Python", category: "Language" },
        { id: 22, name: "IoT Microcontrollers", category: "Hardware" },
        { id: 23, name: "pH & TDS Sensors", category: "Sensors" },
        { id: 24, name: "Turbidity Sensors", category: "Sensors" },
        { id: 25, name: "Telemetry Logging", category: "Data" },
      ],
    },
    {
      id: 5,
      slug: "intra-college-event-web-app",
      title: "Intra-College Event Web Application (Technoverse)",
      tagline: "Framer-Powered Live Event Coordination & Schedule Platform",
      year: "2026",
      organization: "PSGCAS",
      description:
        "A dedicated responsive event platform constructed for an inter-college technical symposium to facilitate seamless schedule tracking, rulebook access, and registration routing.",
      problem:
        "Fest participants frequently miss event timings or venue updates when relying on printed circulars or cluttered chat groups.",
      solution:
        "Designed and deployed a responsive, high-performance web application featuring streamlined navigation, schedule timetables, and mobile-optimized event cards.",
      contribution:
        "Architected site hierarchy in Framer, implemented dynamic layouts, and ensured zero-lag performance on mobile networks.",
      measurable_results:
        "Supported campus-wide symposium attendees with instant schedule access.",
      github_url: undefined,
      live_url: "https://technoverse.framer.website",
      featured: false,
      display_order: 5,
      primary_category: "SOFTWARE",
      technologies: [
        { id: 26, name: "Framer", category: "Design & Web" },
        { id: 27, name: "Responsive UI/UX", category: "Frontend" },
        { id: 28, name: "Event Architecture", category: "Systems" },
      ],
    },
  ],
  skill_categories: [
    {
      id: 1,
      name: "Programming Languages",
      slug: "programming",
      description: "Core algorithmic and systems languages",
      display_order: 1,
      skills: [
        { id: 1, name: "Python", icon_slug: "python", is_featured: true, display_order: 1 },
        { id: 2, name: "Java", icon_slug: "coffee", is_featured: true, display_order: 2 },
        { id: 3, name: "SQL", icon_slug: "database", is_featured: true, display_order: 3 },
        { id: 4, name: "C++", icon_slug: "code", is_featured: false, display_order: 4 },
        { id: 5, name: "JavaScript / Next.js", icon_slug: "globe", is_featured: true, display_order: 5 },
      ],
    },
    {
      id: 2,
      name: "Frontend & Web",
      slug: "frontend",
      description: "Modern web interfaces, styling, and UX",
      display_order: 2,
      skills: [
        { id: 6, name: "Next.js", icon_slug: "layers", is_featured: true, display_order: 1 },
        { id: 7, name: "HTML5", icon_slug: "layout", is_featured: true, display_order: 2 },
        { id: 8, name: "CSS3", icon_slug: "palette", is_featured: true, display_order: 3 },
        { id: 9, name: "WordPress", icon_slug: "file-text", is_featured: false, display_order: 4 },
        { id: 10, name: "Framer", icon_slug: "box", is_featured: false, display_order: 5 },
        { id: 11, name: "Figma", icon_slug: "figma", is_featured: true, display_order: 6 },
      ],
    },
    {
      id: 3,
      name: "Backend & APIs",
      slug: "backend",
      description: "Scalable REST APIs and microservice patterns",
      display_order: 3,
      skills: [
        { id: 12, name: "FastAPI", icon_slug: "zap", is_featured: true, display_order: 1 },
        { id: 13, name: "Django", icon_slug: "server", is_featured: true, display_order: 2 },
        { id: 14, name: "RESTful APIs", icon_slug: "share-2", is_featured: true, display_order: 3 },
        { id: 15, name: "JWT Authentication", icon_slug: "shield-check", is_featured: true, display_order: 4 },
      ],
    },
    {
      id: 4,
      name: "Databases & ORM",
      slug: "databases",
      description: "Relational, document, and persistent storage",
      display_order: 4,
      skills: [
        { id: 16, name: "PostgreSQL", icon_slug: "database", is_featured: true, display_order: 1 },
        { id: 17, name: "MySQL", icon_slug: "database", is_featured: true, display_order: 2 },
        { id: 18, name: "MongoDB", icon_slug: "database", is_featured: true, display_order: 3 },
        { id: 19, name: "Oracle SQL", icon_slug: "hard-drive", is_featured: false, display_order: 4 },
        { id: 20, name: "SQLAlchemy", icon_slug: "code", is_featured: true, display_order: 5 },
      ],
    },
    {
      id: 5,
      name: "AI, Machine Learning & Data",
      slug: "ai-data",
      description: "LLMs, predictive modeling, and business analytics",
      display_order: 5,
      skills: [
        { id: 21, name: "OpenAI API (GPT-5.5)", icon_slug: "cpu", is_featured: true, display_order: 1 },
        { id: 22, name: "Power BI", icon_slug: "bar-chart-2", is_featured: true, display_order: 2 },
        { id: 23, name: "Tableau", icon_slug: "pie-chart", is_featured: true, display_order: 3 },
        { id: 24, name: "Excel (Microsoft 365)", icon_slug: "table", is_featured: true, display_order: 4 },
        { id: 25, name: "Predictive Modeling", icon_slug: "trending-up", is_featured: true, display_order: 5 },
        { id: 26, name: "Anomaly Detection", icon_slug: "alert-triangle", is_featured: true, display_order: 6 },
        { id: 27, name: "Data Analysis", icon_slug: "activity", is_featured: true, display_order: 7 },
      ],
    },
    {
      id: 6,
      name: "IoT & Embedded Systems",
      slug: "iot-systems",
      description: "Telemetry, hardware sensors, and systems programming",
      display_order: 6,
      skills: [
        { id: 28, name: "IoT Architecture", icon_slug: "radio", is_featured: true, display_order: 1 },
        { id: 29, name: "Sensor Telemetry (pH, TDS, Temp)", icon_slug: "thermometer", is_featured: true, display_order: 2 },
        { id: 30, name: "Microcontrollers", icon_slug: "cpu", is_featured: true, display_order: 3 },
        { id: 31, name: "Linux Shell Programming", icon_slug: "terminal", is_featured: true, display_order: 4 },
      ],
    },
    {
      id: 7,
      name: "Tools & Deployment",
      slug: "tools-deployment",
      description: "Source control, cloud hosting, and CI/CD pipelines",
      display_order: 7,
      skills: [
        { id: 32, name: "GitHub", icon_slug: "github", is_featured: true, display_order: 1 },
        { id: 33, name: "Vercel", icon_slug: "cloud", is_featured: true, display_order: 2 },
        { id: 34, name: "Render", icon_slug: "server", is_featured: true, display_order: 3 },
        { id: 35, name: "Hostinger", icon_slug: "globe", is_featured: false, display_order: 4 },
        { id: 36, name: "SEO & Performance Tools", icon_slug: "search", is_featured: false, display_order: 5 },
      ],
    },
    {
      id: 8,
      name: "AI Development Accelerators",
      slug: "ai-dev-tools",
      description: "AI-assisted coding environments and rapid builders",
      display_order: 8,
      skills: [
        { id: 37, name: "Anti-Gravity", icon_slug: "sparkles", is_featured: true, display_order: 1 },
        { id: 38, name: "Bolt.new", icon_slug: "zap", is_featured: true, display_order: 2 },
        { id: 39, name: "Lovable.ai", icon_slug: "heart", is_featured: true, display_order: 3 },
      ],
    },
    {
      id: 9,
      name: "Engineering Practices & Soft Skills",
      slug: "soft-skills",
      description: "Design thinking, facilitation, and agile methodologies",
      display_order: 9,
      skills: [
        { id: 40, name: "Adaptive Learner", icon_slug: "book-open", is_featured: false, display_order: 1 },
        { id: 41, name: "Team Facilitator", icon_slug: "users", is_featured: false, display_order: 2 },
        { id: 42, name: "Design Thinker", icon_slug: "compass", is_featured: false, display_order: 3 },
        { id: 43, name: "Self-Driven Problem Solver", icon_slug: "target", is_featured: false, display_order: 4 },
      ],
    },
  ],
  certifications: [
    {
      id: 1,
      name: "Python for Data Science",
      issuer: "NPTEL",
      issue_date: "2024",
      image_url: "/certificates/NPTEL/Python For Data Science.jpg",
      pdf_url: "/certificates/NPTEL/Python For Data Science.pdf",
      is_featured: true,
      category: "AI & Data",
      display_order: 1,
    },
    {
      id: 2,
      name: "Data Science 101",
      issuer: "IBM",
      issue_date: "2024",
      image_url: "/certificates/IBM/IBM- Data Science.jpg",
      pdf_url: "/certificates/IBM/IBM- Data Science.pdf",
      is_featured: true,
      category: "AI & Data",
      display_order: 2,
    },
    {
      id: 3,
      name: "Linux Shell Programming",
      issuer: "PSG College of Arts & Science",
      issue_date: "2024",
      image_url: "/certificates/PSGCAS/linux.jpg",
      pdf_url: "/certificates/PSGCAS/linux.pdf",
      is_featured: true,
      category: "Systems",
      display_order: 3,
    },
    {
      id: 4,
      name: "Power BI for Beginners",
      issuer: "Simplilearn",
      issue_date: "2024",
      image_url: "/certificates/Simpilearn/Power BI for Beginners_page-0001.jpg",
      pdf_url: "/certificates/Simpilearn/Power BI for Beginners.pdf",
      is_featured: true,
      category: "AI & Data",
      display_order: 4,
    },
    {
      id: 5,
      name: "Network Security",
      issuer: "Great Learning",
      issue_date: "2024",
      image_url: "/certificates/Great Learning/Great Learning.jpg",
      pdf_url: "/certificates/Great Learning/Great Learning.pdf",
      is_featured: true,
      category: "Security",
      display_order: 5,
    },
    {
      id: 6,
      name: "Fundamentals of Digital Marketing",
      issuer: "Google",
      issue_date: "2023",
      image_url: "/certificates/Google/google certficate.jpg",
      pdf_url: "/certificates/Google/google certficate.pdf",
      is_featured: true,
      category: "Marketing & Strategy",
      display_order: 6,
    },
    {
      id: 7,
      name: "AI and Business Strategy: Case Studies",
      issuer: "LinkedIn",
      issue_date: "2024",
      image_url:
        "/certificates/LinkedIn/Artificial Intelligence and Business Strategy Case Studies_page-0001.jpg",
      pdf_url:
        "/certificates/LinkedIn/Artificial Intelligence and Business Strategy Case Studies.pdf",
      is_featured: true,
      category: "AI & Strategy",
      display_order: 7,
    },
    {
      id: 8,
      name: "Learning Full Stack Development",
      issuer: "Infosys Springboard / Wingspan",
      issue_date: "August 19, 2026",
      verification_url: "https://verify.onwingspan.com",
      image_url: "/certificates/FSD.png",
      pdf_url: "/certificates/FSD.pdf",
      is_featured: true,
      category: "Software Engineering",
      display_order: 8,
    },
    {
      id: 9,
      name: "NodeJS Case Study - Movie App on Node JS & MongoDB",
      issuer: "Infosys Springboard / Wingspan",
      issue_date: "August 19, 2026",
      verification_url: "https://verify.onwingspan.com",
      image_url: "/certificates/node.png",
      pdf_url: "/certificates/node.pdf",
      is_featured: true,
      category: "Software Engineering",
      display_order: 9,
    },
    {
      id: 10,
      name: "Learning Excel (Microsoft 365)",
      issuer: "LinkedIn",
      issue_date: "2024",
      image_url:
        "/certificates/LinkedIn/Learning Excel Desktop Microsoft 365_page-0001.jpg",
      pdf_url: "/certificates/LinkedIn/Learning Excel Desktop Microsoft 365.pdf",
      is_featured: false,
      category: "Analytics",
      display_order: 10,
    },
    {
      id: 11,
      name: "How to Talk to Anyone (Blinkist Summary)",
      issuer: "LinkedIn",
      issue_date: "2024",
      image_url:
        "/certificates/LinkedIn/How to Talk to Anyone Blinkist Summary_page-0001.jpg",
      pdf_url: "/certificates/LinkedIn/How to Talk to Anyone Blinkist Summary.pdf",
      is_featured: false,
      category: "Professional Skills",
      display_order: 11,
    },
    {
      id: 12,
      name: "Ethical Hacking for Beginners",
      issuer: "Simplilearn",
      issue_date: "2024",
      image_url:
        "/certificates/Simpilearn/Ethical hacking for beginners_page-0001.jpg",
      pdf_url: "/certificates/Simpilearn/Ethical hacking for beginners.pdf",
      is_featured: false,
      category: "Security",
      display_order: 12,
    },
    {
      id: 13,
      name: "Blockchain Developer Training",
      issuer: "Simplilearn",
      issue_date: "2024",
      image_url: undefined,
      pdf_url: "/certificates/Simpilearn/Blockchain Developer Training.pdf",
      is_featured: false,
      category: "Systems",
      display_order: 13,
    },
    {
      id: 14,
      name: "Explore Automation Development with UiPath Studio",
      issuer: "UiPath",
      issue_date: "2024",
      image_url:
        "/certificates/UiPath/Explore Automation Development with UiPath Studio .jpg",
      pdf_url:
        "/certificates/UiPath/Explore Automation Development with UiPath Studio .pdf",
      is_featured: false,
      category: "RPA & Automation",
      display_order: 14,
    },
    {
      id: 15,
      name: "Build Your First Process with Studio",
      issuer: "UiPath",
      issue_date: "2024",
      image_url: "/certificates/UiPath/Build Your First Process with Studio.jpg",
      pdf_url: "/certificates/UiPath/Build Your First Process with Studio.pdf",
      is_featured: false,
      category: "RPA & Automation",
      display_order: 15,
    },
    {
      id: 16,
      name: "Control Flow in Studio",
      issuer: "UiPath",
      issue_date: "2024",
      image_url: "/certificates/UiPath/Control Flow in Studio.jpg",
      pdf_url: "/certificates/UiPath/Control Flow in Studio.pdf",
      is_featured: false,
      category: "RPA & Automation",
      display_order: 16,
    },
    {
      id: 17,
      name: "Variables, Constants and Arguments in Studio",
      issuer: "UiPath",
      issue_date: "2024",
      image_url:
        "/certificates/UiPath/Variables Constants and Arguments in Studio.jpg",
      pdf_url:
        "/certificates/UiPath/Variables Constants and Arguments in Studio.pdf",
      is_featured: false,
      category: "RPA & Automation",
      display_order: 17,
    },
    {
      id: 18,
      name: "Excel Automation with Modern Experience in Studio",
      issuer: "UiPath",
      issue_date: "2024",
      image_url:
        "/certificates/UiPath/Excel Automation with the Modern Experience in Studio.jpg",
      pdf_url:
        "/certificates/UiPath/Excel Automation with the Modern Experience in Studio.pdf",
      is_featured: false,
      category: "RPA & Automation",
      display_order: 18,
    },
    {
      id: 19,
      name: "User Interface (UI) Automation with Modern Design in Studio",
      issuer: "UiPath",
      issue_date: "2024",
      image_url:
        "/certificates/UiPath/User Interface (UI) Automation with Modern Design in Studio.jpg",
      pdf_url:
        "/certificates/UiPath/User Interface (UI) Automation with Modern Design in Studio .pdf",
      is_featured: false,
      category: "RPA & Automation",
      display_order: 19,
    },
    {
      id: 20,
      name: "Attended Automation for RPA Developers",
      issuer: "UiPath",
      issue_date: "2024",
      image_url:
        "/certificates/UiPath/Attended Automation for RPA Developers.jpg",
      pdf_url:
        "/certificates/UiPath/Attended Automation for RPA Developers.pdf",
      is_featured: false,
      category: "RPA & Automation",
      display_order: 20,
    },
    {
      id: 21,
      name: "Train ML Models for Document Understanding",
      issuer: "UiPath",
      issue_date: "2024",
      image_url:
        "/certificates/UiPath/Train ML Models for Document Understanding.jpg",
      pdf_url:
        "/certificates/UiPath/Train ML Models for Document Understanding.pdf",
      is_featured: false,
      category: "RPA & Automation",
      display_order: 21,
    },
    {
      id: 22,
      name: "Managerial Skills, Leadership & Team Building for Startups",
      issuer: "Wadhwani Foundation (NABARD-funded)",
      issue_date: "2025",
      image_url: "/certificates/Wandhwani/Wandhawni_page-0001.jpg",
      pdf_url: "/certificates/Wandhwani/Wandhawni.pdf",
      is_featured: false,
      category: "Leadership & Startups",
      display_order: 22,
    },
  ],
  achievements: [
    {
      id: 1,
      title: "Best Performance Award",
      event: "IoT-Based Technology Innovative Expo",
      year: "2026",
      description:
        "Awarded Best Performance for demonstrating hardware-software technical excellence, innovative architecture, and real-time sensor processing in IoT solutions.",
      category: "Award",
      display_order: 1,
    },
    {
      id: 2,
      title: "Best Minimum Viable Product (MVP)",
      event: "Hack-Arti-Thon 2.0 (24-Hour National Hackathon)",
      year: "2026",
      description:
        "Recognized for outstanding rapid prototyping, architectural execution, and delivery of a high-impact working MVP during an intense 24-hour national hackathon.",
      category: "Award",
      display_order: 2,
    },
    {
      id: 3,
      title: "Student Coordinator – Hackverse 2026",
      event: "Hackverse 2026 Mini Hackathon",
      year: "2026",
      description:
        "Served as an active student coordinator facilitating problem statement ideation, team support, and innovation-driven development during the hackathon.",
      category: "Leadership",
      display_order: 3,
    },
    {
      id: 4,
      title: "NABARD-Funded Entrepreneurship & Leadership Training",
      event: "Wadhwani Foundation / NABARD",
      year: "2025",
      description:
        "Completed specialized bootcamp on Managerial Skills, Agile Leadership, and Team Building for Early-Stage Startups.",
      category: "Professional Development",
      display_order: 4,
    },
  ],
  hackathons: [
    {
      id: 1,
      title: "Hack-Arti-Thon 2.0",
      role_or_focus: "National 24-Hour Hackathon – Awarded Best MVP",
      year: "2026",
      description:
        "Engineered and delivered a fully functional MVP under strict 24-hour time constraints, showcasing rapid architecture design and problem solving.",
      display_order: 1,
    },
    {
      id: 2,
      title: "Socio-Tech Hackathon",
      role_or_focus: "Anti-Drug Societal Challenge Problem Statement",
      year: "2024",
      description:
        "Engineered technical software solutions addressing real-world community awareness and anti-drug tracking challenges.",
      display_order: 2,
    },
    {
      id: 3,
      title: "Smart India Hackathon (SIH)",
      role_or_focus: "Student Dropout Analysis & AICTE Challenges",
      year: "2023",
      description:
        "Collaborated in building analytical solutions for academic retention patterns, student dropout factor analysis, and AICTE innovation challenges.",
      display_order: 3,
    },
    {
      id: 4,
      title: "Hackverse 2026 Mini Hackathon",
      role_or_focus: "Student Coordinator & Technical Facilitator",
      year: "2026",
      description:
        "Coordinated technical operations, mentorship sessions, and ideation tracks for multi-disciplinary student hacker teams.",
      display_order: 4,
    },
  ],
  activities: [
    {
      id: 1,
      title: "Innovation & Entrepreneurship Bootcamp 2.0",
      role: "Resource Person & Technical Speaker",
      year: "2026",
      description:
        "Delivered specialized sessions on digital outreach strategies, technical product development, and modern entrepreneurship concepts.",
      display_order: 1,
    },
    {
      id: 2,
      title: "Entrepreneur 2026",
      role: "Official Pitch Evaluator",
      year: "2026",
      description:
        "Acted as an evaluator assessing student startup pitches, technical feasibility of prototypes, and innovative product frameworks.",
      display_order: 2,
    },
    {
      id: 3,
      title: "Design Thinking Workshops & Campus Events",
      role: "Session Facilitator & Event Coordinator",
      year: "2025",
      description:
        "Delivered interactive sessions on Design Thinking methodologies, user-centered prototyping, and coordinated departmental technical events.",
      display_order: 3,
    },
  ],
  resume: {
    id: 1,
    title: "Tharun Vaibhav S S – Primary Technical Resume",
    filename: "Tharun_Vaibhav_Resume.pdf",
    file_path: "/resumes/Tharun_Vaibhav_Resume.pdf",
    is_primary: true,
    uploaded_at: "September 2026",
  },
};
